// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6g1JdhpRzvT84qLw7fg3P0IHla9UjFw',
    appId: '1:564275998549:android:88cebd344ad0abf48389dc',
    messagingSenderId: '564275998549',
    projectId: 'masheed-d942d',
    databaseURL: 'https://masheed-d942d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'masheed-d942d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE1dHeRBvzEHURUoPSVRb00lwYilpAI4A',
    appId: '1:564275998549:ios:ad7520296577a8f68389dc',
    messagingSenderId: '564275998549',
    projectId: 'masheed-d942d',
    databaseURL: 'https://masheed-d942d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'masheed-d942d.appspot.com',
    androidClientId: '564275998549-ciusva96h4fibgf4bbfgf2trmcd3u1ot.apps.googleusercontent.com',
    iosClientId: '564275998549-u16u39ookv518tje2uv6hi7abu1b3vvf.apps.googleusercontent.com',
    iosBundleId: 'com.tatweer.almasheed',
  );
}
